title:            Nom Nom Brewery
description:      Humle, malt, humle, jäst, humle, vatten 
url:              http://www.nomnombrewery.com
signoff:          Henric
disqus_shortname: nomnombrewery # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-42731887-1

links:
  - name:         Start
    url:          /
  - name:         Arkiv
    url:          /posts
#  - name:         Recept
#    url:          /recipes
  - name:         Bryggeriet
    url:          /about
pygments:         true
permalink:        pretty
markdown:         rdiscount
timezone:         Europe/Stockholm
rdiscount:
  extensions:     [smart]
